# How to Write a Git Commit Message: https://chris.beams.io/posts/git-commit/
# Ref: https://github.com/marketplace/actions/opinionated-commit-message
name: 'Check commit message style'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - master
      - 'dev/*'

jobs:
  check-commit-message-style:
    name: Check commit message style
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: mristin/opinionated-commit-message@v1.0.0
